version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --chdir=/app --log-level=info --log-file=./logs/gunicorn.log --access-logfile=./logs/gunicorn-access.log
    depends_on:
      - postgres

    env_file:
      #- ./envs/common/django.env
      - ./env
    volumes:
      - .:/app
    expose:
      - 8000
    links:
      - postgres
    networks:
      - database1_network
      - nginx_network


  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile